### ISSUE TITLE
Canyon Tracker

### ISSUE THREAD

**Issue by ncitron** [a16z/magi#190]
- [x] Set withdrawals to empty array ([spec](https://github.com/ethereum-optimism/optimism/blob/develop/specs/derivation.md#building-individual-payload-attributes))
- [x] Channel ordering fix ([spec](https://github.com/ethereum-optimism/optimism/blob/develop/specs/derivation.md#reading))
- [x] Implement blocks v2 gossip topic ([spec](https://github.com/ethereum-optimism/optimism/blob/develop/specs/rollup-node-p2p.md#gossip-topics))
